spring.application.name=fintech

# ============================================================
# BANCO DE DADOS - Oracle FIAP
# ============================================================
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=rm567249
spring.datasource.password=270805
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta
server.port=8080
